version: '3.1'

services:

  ember:
    build: ember-dev/
    image: oapass/ember-dev
    container_name: ember
    env_file: .env
    volumes:
      - ../:/app:Z
      - /app/node_modules
    ports:
      - '${EMBER_PORT}:${EMBER_PORT}'
    networks:
      - back

  fcrepo:
    image: oapass/fcrepo:4.7.5-3.5@sha256:bb44fff182ace1d0d57372f297cbab8cc04c662db2d10a061213178b7c0c9bba
    container_name: fcrepo
    env_file: .harvard_env
    ports:
      - "${FCREPO_PORT}:${FCREPO_PORT}"
      - "${FCREPO_DEBUG_PORT}:${FCREPO_DEBUG_PORT}"
    networks:
      - front
      - back
    volumes:
      - passdata-harvard:/data
    depends_on:
      - assets
      - activemq

  activemq:
    image: oapass/activemq:20180618@sha256:e3cd47a1bc4c21899fc34e5ac7198f6c069f4148296bad0ce619cc2bdda5f435
    container_name: activemq
    env_file: .harvard_env
    ports:
      - "${ACTIVEMQ_JMS_PORT}:${ACTIVEMQ_JMS_PORT}"
      - "${ACTIVEMQ_STOMP_PORT}:${ACTIVEMQ_STOMP_PORT}"
      - "${ACTIVEMQ_WEBCONSOLE_PORT}:${ACTIVEMQ_WEBCONSOLE_PORT}"
    networks:
      - front
      - back

  static-html:
    image: oapass/static-html:20190829-9e3e344@sha256:33b5d79fbdc3adda35b536eedac9897a14b751a44c50d96367021789119e485e
    container_name: static-html
    env_file: .harvard_env
    ports:
      - "${STATIC_HTML_PORT}:${STATIC_HTML_PORT}"
    networks:
      - back
      - front

  proxy:
    image: oapass/httpd-proxy:201900508@sha256:a915ada2286a551d32b0494d4ce874ba7fe204c07f029cc9bba5e05b2a9087fc
    container_name: proxy
    networks:
     - front
     - back
    ports:
     - "80:80"
     - "443:443"

  idp:
    image: oapass/idp:20190821-harvard@sha256:8d5de05ef52eb2b7ad8822087c55bd1ea4069ecb3545cd4712a85469c7665a82
    container_name: idp
    depends_on:
     - ldap
    environment:
     - JETTY_MAX_HEAP=64m
     - JETTY_BROWSER_SSL_KEYSTORE_PASSWORD=password
     - JETTY_BACKCHANNEL_SSL_KEYSTORE_PASSWORD=password
    expose:
     - "4443"
    networks:
     - back
    secrets:
     - source: idp_backchannel
     - source: idp_browser
     - source: idp_encryption
     - source: idp_signing
     - source: idp_sealer

  ldap:
    image: oapass/ldap:20190821-harvard@sha256:15cd758aa16b7cd59ba8c457b9981b261848d3a2901b9eacb36fb686ab301566
    container_name: ldap
    networks:
     - back

  sp:
    image: oapass/sp:20190813@sha256:d75554dd82191ec3201494a2c0db5ba632d0e37141bba6561b5d48fdee916f38
    container_name: sp
    networks:
     - back
    secrets:
     - source: sp_key

  indexer:
    image: oapass/indexer:0.0.18-3.4-1@sha256:3375ea702e0a1c7a5e0e7e06635d28e49af436aeb1c3d88a03d4cb494d7b40bf
    container_name: indexer
    env_file: .harvard_env
    networks:
      - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3@sha256:ccfad77c0731c010e6ff8c43b4ab50f5ce90c0fa4e65846530779c5c6707c20a
    container_name: elasticsearch
    env_file: .harvard_env
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - passdata-harvard:/usr/share/elasticsearch/data
    ports:
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - front
      - back
    depends_on:
      - assets

  assets:
    image: birkland/assets:harvard-base-2019-08-28_3.4@sha256:8e0ff1b51063663b4e48512622acc2edcac78e65e8f88dfd8ee101903939fe23
    volumes:
      - passdata-harvard:/data

  authz:
    image: oapass/authz:0.5.0-3.5@sha256:c1568ddc81a8731255ddd41a966e86cb2070854d13ffad15f54c9b3b3b63ab03
    container_name: authz
    env_file: .harvard_env
    networks:
      - back

  schemaservice:
    image: oapass/schema-service:v0.6.0-1-g60e99b8@sha256:9c8cee614b5ce399068a383cece5ced4396372023cc3477561e2e7df2474dfae
    container_name: schemaservice
    env_file: .harvard_env
    ports:
      - "${SCHEMA_SERVICE_PORT}:${SCHEMA_SERVICE_PORT}"
    networks:
      - front
      - back

  policyservice:
    image: oapass/policy-service:v0.2.0@sha256:8a2f4236b700077511f240fc302dc40450dafdb58db4570b20aa31be7a80ae93
    container_name: policyservice
    env_file: .harvard_env
    ports:
      - "${POLICY_SERVICE_PORT}:${POLICY_SERVICE_PORT}"
    networks:
      - front
      - back

  doiservice:
    image: oapass/doi-service:version1.0.0@sha256:a82a1b60b4bae17b9a5628ed3d65501000d576ef3ba6bc3ffe4cbf9138eba82d
    container_name: doiservice
    env_file: .harvard_env
    ports:
      - "${PASS_DOI_SERVICE_PORT}:8080"
    networks:
      - front
      - back

volumes:
  passdata-harvard:
    driver: local
  mailstate-harvard:
    driver: local
  maildata-harvard:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  idp_backchannel:
    file: ./secrets/idp/idp-backchannel.p12
  idp_browser:
    file: ./secrets/idp/idp-browser.p12
  idp_encryption:
    file: ./secrets/idp/idp-encryption.key
  idp_signing:
    file: ./secrets/idp/idp-signing.key
  idp_sealer:
    file: ./secrets/idp/sealer.jks
  sp_key:
    file: ./secrets/sp/sp-key.pem
