name: Release PASS-UI

on:
  workflow_dispatch:
    inputs:
      releaseversion:
        required: true
        description: Version to release (e.g. 0.4.0)
      nextversion:
        required: true
        description: Next development version (e.g. 0.5.0-SNAPSHOT)
  workflow_call:
    inputs:
      releaseversion:
        required: true
        description: Version to release (e.g. 0.4.0)
        type: string
      nextversion:
        required: true
        description: Next development version (e.g. 0.5.0-SNAPSHOT)
        type: string

jobs:
  release:
    if: github.repository == 'eclipse-pass/pass-ui'
    runs-on: ubuntu-latest

    env:
      ENV_FILE: https://raw.githubusercontent.com/eclipse-pass/pass-docker/main/.env
      DOCKER_IMAGE_NAME: ghcr.io/eclipse-pass/pass-ui

    steps:
      - uses: actions/checkout@v4

      - name: Config git user
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update project version
        run: |
          pnpm install --frozen-lockfile
          pnpm version --new-version ${{ inputs.releaseversion }}

      - name: Tag release
        run: git tag ${{ inputs.releaseversion }}

      - name: Grab pass-docker's .env file
        run: |
          wget $ENV_FILE
        shell: bash

      - name: Build Release image
        uses: eclipse-pass/main/.github/actions/node-build@main
        with:
          repository_dir: ${{ github.workspace }}
          env_path: ${{ github.workspace }}/.env

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Retag and push
        run: |
          docker push $DOCKER_IMAGE_NAME:${{ inputs.releaseversion }}

      - name: Update project version
        run: pnpm version --new-version ${{ inputs.nextversion }}

      - name: Build Next Version image
        uses: eclipse-pass/main/.github/actions/node-build@main
        with:
          repository_dir: ${{ github.workspace }}
          env_path: ${{ github.workspace }}/.env

      # Commits made to branch specified in workflow_dispatch, push that branch if possible
      - name: Push release commits to GH
        if: github.ref_type == 'branch' && github.ref_protected == false
        run: git push origin ${{ github.ref_name }}

      # Push the release tag we made above
      - name: Push release tag to GH
        run: git push origin ${{ inputs.releaseversion }}

      - name: Push next dev version image
        run: |
          docker push $DOCKER_IMAGE_NAME:${{ inputs.nextversion }}
